name: Test Issue Processor
on:
  issues:
    types: [opened]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Issue Processor
        uses: ./action.yml
        with:
          ai_model: 'gpt-4-1106-preview'
          max_tokens: '1000'
